name: AzCLItest/AzCLItest
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Build
      run: dotnet build
    - run: dotnet test --logger trx --results-directory "${{ runner.temp }}"
    - uses: NasAmin/trx-parser@v0.5.0
      if: always()
      with:
        TRX_PATH: "${{ runner.temp }}"
        REPO_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
